# Generated by Django 4.2.5 on 2025-07-11 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentchat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='level',
            field=models.CharField(choices=[('100', '100 Level'), ('200', '200 Level'), ('300', '300 Level'), ('400', '400 Level'), ('500', '500 Level')], max_length=3),
        ),
    ]
