# Generated by Django 4.2.5 on 2025-06-21 11:36

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_statement', models.FileField(upload_to='personal_statement/')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UndergraduateApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=15)),
                ('day_of_birth', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31')], max_length=15)),
                ('month_of_birth', models.CharField(choices=[('Ja', 'January'), ('Fe', 'Febraury'), ('Ma', 'March'), ('Ap', 'April'), ('My', 'May'), ('Jn', 'June'), ('Jy', 'July'), ('Ag', 'August'), ('Sp', 'September'), ('Oc', 'October'), ('Nv', 'November'), ('Dc', 'December')], max_length=15)),
                ('year_of_birth', models.CharField(choices=[('23', '2023'), ('22', '2022'), ('21', '2021'), ('20', '2020'), ('19', '2019'), ('18', '2018'), ('17', '2017'), ('16', '2016'), ('15', '2015'), ('14', '2014'), ('13', '2013'), ('12', '2012'), ('11', '2011'), ('10', '2010')], max_length=15)),
                ('email', models.EmailField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('address_1', models.CharField(max_length=255)),
                ('address_2', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state_province', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=255)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('school_name', models.CharField(max_length=255)),
                ('school_address_1', models.CharField(max_length=255)),
                ('school_address_2', models.CharField(max_length=255)),
                ('school_city', models.CharField(max_length=255)),
                ('school_state_province', models.CharField(max_length=255)),
                ('school_postal_code', models.CharField(max_length=255)),
                ('school_year_graduated', models.CharField(max_length=255)),
                ('emergency_first_name', models.CharField(max_length=255)),
                ('emergency_last_name', models.CharField(max_length=255)),
                ('emergency_email', models.EmailField(max_length=255)),
                ('emergency_phone_number', models.CharField(max_length=255)),
                ('emergency_address_1', models.CharField(max_length=255)),
                ('emergency_address_2', models.CharField(max_length=255)),
                ('emergency_city', models.CharField(max_length=255)),
                ('emergency_postal_code', models.CharField(max_length=255)),
                ('emergency_country', django_countries.fields.CountryField(max_length=2)),
                ('emergency_relationship', models.CharField(choices=[('B', 'Brother'), ('S', 'Sister'), ('F', 'Father'), ('M', 'Mother'), ('O', 'Other')], max_length=15)),
                ('referee_first_name', models.CharField(max_length=255)),
                ('referee_last_name', models.CharField(max_length=255)),
                ('referee_email', models.EmailField(max_length=255)),
                ('referee_phone_number', models.CharField(max_length=255)),
                ('referee_address_1', models.CharField(max_length=255)),
                ('referee_address_2', models.CharField(max_length=255)),
                ('referee_city', models.CharField(max_length=255)),
                ('referee_postal_code', models.CharField(max_length=255)),
                ('referee_state_province', models.CharField(max_length=255)),
                ('referee_country', django_countries.fields.CountryField(max_length=2)),
                ('personal_statement', models.FileField(upload_to='documents/')),
                ('image', models.ImageField(upload_to='Images/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.course')),
            ],
        ),
        migrations.CreateModel(
            name='ScholarshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=15)),
                ('day_of_birth', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31')], max_length=15)),
                ('month_of_birth', models.CharField(choices=[('Ja', 'January'), ('Fe', 'Febraury'), ('Ma', 'March'), ('Ap', 'April'), ('My', 'May'), ('Jn', 'June'), ('Jy', 'July'), ('Ag', 'August'), ('Sp', 'September'), ('Oc', 'October'), ('Nv', 'November'), ('Dc', 'December')], max_length=15)),
                ('year_of_birth', models.CharField(choices=[('23', '2023'), ('22', '2022'), ('21', '2021'), ('20', '2020'), ('19', '2019'), ('18', '2018'), ('17', '2017'), ('16', '2016'), ('15', '2015'), ('14', '2014'), ('13', '2013'), ('12', '2012'), ('11', '2011'), ('10', '2010')], max_length=15)),
                ('email', models.EmailField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('address_1', models.CharField(max_length=255)),
                ('address_2', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state_province', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=255)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('about_yourself', models.CharField(max_length=255)),
                ('career_plans', models.CharField(max_length=255)),
                ('role_model', models.CharField(max_length=255)),
                ('reasons_for_course_school_choice', models.CharField(max_length=255)),
                ('why_you_deserve_scholarship', models.CharField(max_length=255)),
                ('your_greatest_achievement', models.CharField(max_length=255)),
                ('your_strenths', models.CharField(max_length=255)),
                ('your_weaknesses', models.CharField(max_length=255)),
                ('challenge_faced_overcomed', models.CharField(max_length=255)),
                ('your_leadership_experience', models.CharField(max_length=255)),
                ('activities_involved_in_school_community', models.CharField(max_length=255)),
                ('additional_statement', models.CharField(max_length=255)),
                ('course_applied', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.course')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='core.faculty')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.department'),
        ),
    ]
