# Generated by Django 4.2.5 on 2025-06-28 14:39

import core.models.users
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user_type', models.CharField(choices=[(1, 'Management'), (2, 'AcademicStaff'), (3, 'NonAcademicStaff'), (4, 'Student'), (5, 'AspirantStudent')], default=1, max_length=1)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', core.models.users.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AcademicCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=20)),
                ('semester', models.CharField(choices=[('First', 'First Semester'), ('Second', 'Second Semester')], max_length=10)),
                ('is_current', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('unit', models.PositiveIntegerField()),
                ('level', models.PositiveSmallIntegerField(choices=[(100, '100 Level'), (200, '200 Level'), (300, '300 Level'), (400, '400 Level'), (500, '500 Level')])),
                ('semester', models.CharField(choices=[('First', 'First Semester'), ('Second', 'Second Semester')], max_length=10)),
                ('category', models.CharField(choices=[('core', 'Core'), ('elective', 'Elective'), ('general', 'General')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseOfStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration_years', models.PositiveIntegerField(default=4)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_statement', models.FileField(upload_to='personal_statement/')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('is_repeat_course', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False)),
                ('academic_calendar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.academiccalendar')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matric_no', models.CharField(max_length=20, unique=True)),
                ('level', models.PositiveIntegerField(choices=[(100, '100 Level'), (200, '200 Level'), (300, '300 Level'), (400, '400 Level'), (500, '500 Level'), (600, '600 Level')])),
                ('date_of_admission', models.DateTimeField(auto_now_add=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
                ('course_of_study', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.courseofstudy')),
            ],
        ),
        migrations.CreateModel(
            name='UndergraduateApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=15)),
                ('dob', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('address_1', models.CharField(max_length=255)),
                ('address_2', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state_province', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=255)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('course_of_study', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.courseofstudy')),
            ],
        ),
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=10)),
                ('ca1', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ca2', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ca3', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('exam', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('grade_point', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('remark', models.TextField(blank=True, null=True)),
                ('is_released', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registered_course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.registeredcourse')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SemesterResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
            ],
        ),
        migrations.CreateModel(
            name='ScholarshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=15)),
                ('day_of_birth', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31')], max_length=15)),
                ('month_of_birth', models.CharField(choices=[('Ja', 'January'), ('Fe', 'Febraury'), ('Ma', 'March'), ('Ap', 'April'), ('My', 'May'), ('Jn', 'June'), ('Jy', 'July'), ('Ag', 'August'), ('Sp', 'September'), ('Oc', 'October'), ('Nv', 'November'), ('Dc', 'December')], max_length=15)),
                ('year_of_birth', models.CharField(choices=[('23', '2023'), ('22', '2022'), ('21', '2021'), ('20', '2020'), ('19', '2019'), ('18', '2018'), ('17', '2017'), ('16', '2016'), ('15', '2015'), ('14', '2014'), ('13', '2013'), ('12', '2012'), ('11', '2011'), ('10', '2010')], max_length=15)),
                ('email', models.EmailField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('address_1', models.CharField(max_length=255)),
                ('address_2', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state_province', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=255)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('about_yourself', models.CharField(max_length=255)),
                ('career_plans', models.CharField(max_length=255)),
                ('role_model', models.CharField(max_length=255)),
                ('reasons_for_course_school_choice', models.CharField(max_length=255)),
                ('why_you_deserve_scholarship', models.CharField(max_length=255)),
                ('your_greatest_achievement', models.CharField(max_length=255)),
                ('your_strenths', models.CharField(max_length=255)),
                ('your_weaknesses', models.CharField(max_length=255)),
                ('challenge_faced_overcomed', models.CharField(max_length=255)),
                ('your_leadership_experience', models.CharField(max_length=255)),
                ('activities_involved_in_school_community', models.CharField(max_length=255)),
                ('additional_statement', models.CharField(max_length=255)),
                ('course_applied', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.courseofstudy')),
            ],
        ),
        migrations.AddField(
            model_name='registeredcourse',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student'),
        ),
        migrations.CreateModel(
            name='NonAcademicStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nonacademicstaff', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='core.faculty')),
            ],
            options={
                'unique_together': {('name', 'faculty')},
            },
        ),
        migrations.AddField(
            model_name='courseofstudy',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_of_study', to='core.department'),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.department'),
        ),
        migrations.CreateModel(
            name='AspirantStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=255)),
                ('address_1', models.CharField(max_length=255)),
                ('address_2', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state_province', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=255)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('admission_status', models.CharField(choices=[('pending', 'Pending'), ('admitted', 'Admitted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('school_name', models.CharField(max_length=255)),
                ('school_address_1', models.CharField(max_length=255)),
                ('school_address_2', models.CharField(max_length=255)),
                ('school_city', models.CharField(max_length=255)),
                ('school_state_province', models.CharField(max_length=255)),
                ('school_postal_code', models.CharField(max_length=255)),
                ('school_year_graduated', models.CharField(max_length=255)),
                ('emergency_first_name', models.CharField(max_length=255)),
                ('emergency_last_name', models.CharField(max_length=255)),
                ('emergency_email', models.EmailField(max_length=255)),
                ('emergency_phone_number', models.CharField(max_length=255)),
                ('emergency_address_1', models.CharField(max_length=255)),
                ('emergency_address_2', models.CharField(max_length=255)),
                ('emergency_city', models.CharField(max_length=255)),
                ('emergency_postal_code', models.CharField(max_length=255)),
                ('emergency_country', django_countries.fields.CountryField(max_length=2)),
                ('emergency_relationship', models.CharField(choices=[('B', 'Brother'), ('S', 'Sister'), ('F', 'Father'), ('M', 'Mother'), ('O', 'Other')], max_length=15)),
                ('referee_first_name', models.CharField(max_length=255)),
                ('referee_last_name', models.CharField(max_length=255)),
                ('referee_email', models.EmailField(max_length=255)),
                ('referee_phone_number', models.CharField(max_length=255)),
                ('referee_address_1', models.CharField(max_length=255)),
                ('referee_address_2', models.CharField(max_length=255)),
                ('referee_city', models.CharField(max_length=255)),
                ('referee_postal_code', models.CharField(max_length=255)),
                ('referee_state_province', models.CharField(max_length=255)),
                ('referee_country', django_countries.fields.CountryField(max_length=2)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('course_applied', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.courseofstudy')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academicstaff', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LevelCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(choices=[(100, '100 Level'), (200, '200 Level'), (300, '300 Level'), (400, '400 Level'), (500, '500 Level')])),
                ('semester', models.CharField(choices=[('First', 'First Semester'), ('Second', 'Second Semester')], max_length=10)),
                ('is_compulsory', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course')),
                ('course_of_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.courseofstudy')),
            ],
            options={
                'unique_together': {('level', 'semester', 'course', 'course_of_study')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='courseofstudy',
            unique_together={('name', 'department')},
        ),
    ]
