# Generated by Django 4.2.5 on 2025-06-28 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonalStatement',
        ),
        migrations.RemoveField(
            model_name='undergraduateapplication',
            name='course_of_study',
        ),
        migrations.DeleteModel(
            name='ScholarshipApplication',
        ),
        migrations.DeleteModel(
            name='UndergraduateApplication',
        ),
    ]
