# Generated by Django 4.2.5 on 2025-06-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_personalstatement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentresult',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='session',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='student',
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.PositiveIntegerField(choices=[(100, '100 Level'), (200, '200 Level'), (300, '300 Level'), (400, '400 Level'), (500, '500 Level')]),
        ),
    ]
