# Generated by Django 4.2.5 on 2025-07-02 11:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_studentschoolfee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentschoolfee',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='studentschoolfee',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='studentschoolfee',
            name='session',
        ),
        migrations.AddField(
            model_name='studentschoolfee',
            name='calendar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.academiccalendar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentschoolfee',
            name='level_at_payment',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SchoolFeeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('school_fee_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schoolfeeitem', to='core.studentschoolfee')),
            ],
        ),
    ]
