# Generated by Django 4.2.5 on 2025-06-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_undergraduateapplication_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='undergraduateapplication',
            name='day_of_birth',
        ),
        migrations.RemoveField(
            model_name='undergraduateapplication',
            name='month_of_birth',
        ),
        migrations.RemoveField(
            model_name='undergraduateapplication',
            name='year_of_birth',
        ),
        migrations.AddField(
            model_name='undergraduateapplication',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
