# Generated by Django 4.2.5 on 2025-07-02 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_studentschoolfee_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentschoolfee',
            old_name='calendar',
            new_name='academic_calendar',
        ),
    ]
