# Generated by Django 4.2.5 on 2025-06-22 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_undergraduateapplication_day_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='undergraduateapplication',
            name='course_of_study',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.courseofstudy'),
            preserve_default=False,
        ),
    ]
