# Generated by Django 4.2.5 on 2025-07-02 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_calendar_studentschoolfee_academic_calendar'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentFeeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RenameModel(
            old_name='StudentSchoolFee',
            new_name='DepartmentSchoolFee',
        ),
        migrations.DeleteModel(
            name='SchoolFeeItem',
        ),
        migrations.AddField(
            model_name='departmentfeeitem',
            name='department_school_fee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.departmentschoolfee'),
        ),
    ]
