# Generated by Django 4.2.5 on 2025-07-02 13:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_departmentfeeitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentschoolfee',
            name='level_at_payment',
        ),
        migrations.RemoveField(
            model_name='departmentschoolfee',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='departmentschoolfee',
            name='status',
        ),
        migrations.RemoveField(
            model_name='departmentschoolfee',
            name='student',
        ),
        migrations.AddField(
        model_name='departmentschoolfee',
        name='department',
        field=models.ForeignKey(
            default=1,
            on_delete=django.db.models.deletion.CASCADE,
            to='core.department',
        ),
        preserve_default=False,
        ),
    ]
