# Generated by Django 4.2.5 on 2025-06-23 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentportal', '0006_aspirantstudent_admission_status'),
        ('core', '0007_course_studentresult_semesterresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentresult',
            name='student',
        ),
        migrations.CreateModel(
            name='RegisteredCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentportal.student')),
            ],
        ),
        migrations.AddField(
            model_name='studentresult',
            name='registered_course',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.registeredcourse'),
            preserve_default=False,
        ),
    ]
