# Generated by Django 4.2.5 on 2025-07-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_departmentschoolfee_level_at_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentschoolfee',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
