# Generated by Django 4.2.5 on 2025-06-23 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentportal', '0006_aspirantstudent_admission_status'),
        ('core', '0008_remove_studentresult_student_registeredcourse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentresult',
            name='course',
        ),
        migrations.AddField(
            model_name='studentresult',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='studentportal.student'),
            preserve_default=False,
        ),
    ]
