# Generated by Django 4.2.5 on 2025-06-23 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import datetime  # ✅ Added import

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_remove_studentresult_course_studentresult_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime.now),  # ✅ Fixed
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='registeredcourse',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registeredcourse',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registeredcourse',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registeredcourse',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registeredcourse',
            name='is_repeat_course',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime.now),  # ✅ Fixed
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentresult',
            name='grade_point',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='is_released',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
