# Generated by Django 4.2.5 on 2025-06-24 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_course_created_at_course_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=20)),
                ('semester', models.CharField(choices=[('First', 'First'), ('Second', 'Second')], max_length=10)),
                ('is_current', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='registeredcourse',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='registeredcourse',
            name='session',
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.PositiveIntegerField(choices=[(100, '100 Level'), (200, '200 Level'), (300, '300 Level'), (400, '400 Level'), (500, '500 Level')]),
        ),
        migrations.AddField(
            model_name='registeredcourse',
            name='academic_calendar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.academiccalendar'),
        ),
    ]
