# Generated by Django 4.2.5 on 2025-07-04 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_course_level_alter_departmentschoolfee_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentschoolfee',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student'),
        ),
    ]
