# Generated by Django 4.2.5 on 2025-06-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_academiccalendar_remove_registeredcourse_semester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='ca3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
