# Generated by Django 4.2.5 on 2025-07-04 08:30

import core.models.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_studentschoolfee_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentschoolfee',
            name='reference',
            field=models.CharField(default=core.models.utils.generate_reference, max_length=20, unique=True),
        ),
    ]
