# Generated by Django 4.2.5 on 2025-06-24 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_studentresult_ca3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredcourse',
            name='academic_calendar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.academiccalendar'),
        ),
    ]
