# Generated by Django 4.2.5 on 2025-07-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_studentschoolfee_reference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentschoolfee',
            old_name='generated_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='studentschoolfee',
            name='last_payment_attempt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentschoolfee',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentschoolfee',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='studentschoolfee',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
