# Generated by Django 4.2.5 on 2025-06-24 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_registeredcourse_academic_calendar'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(choices=[(100, '100 Level'), (200, '200 Level'), (300, '300 Level'), (400, '400 Level'), (500, '500 Level'), (600, '600 Level')])),
                ('semester', models.CharField(choices=[('First', 'First Semester'), ('Second', 'Second Semester')], max_length=10)),
                ('is_compulsory', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course')),
                ('course_of_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.courseofstudy')),
            ],
            options={
                'unique_together': {('level', 'semester', 'course', 'course_of_study')},
            },
        ),
    ]
