# Generated by Django 4.2.5 on 2025-07-04 13:33

import core.models.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_generated_at_studentschoolfee_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentschoolfee',
            name='reference',
            field=models.CharField(default=core.models.utils.generate_reference, max_length=20, unique=True),
        ),
    ]
