# Generated by Django 4.2.5 on 2025-07-04 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_studentschoolfee_reference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentschoolfee',
            old_name='created_at',
            new_name='generated_at',
        ),
    ]
