# Generated by Django 4.2.5 on 2025-07-07 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_failedpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspirantstudent',
            name='admin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aspirant', to=settings.AUTH_USER_MODEL),
        ),
    ]
