# Generated by Django 4.2.5 on 2025-07-08 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_aspirantstudent_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('academic_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.academicstaff')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course')),
            ],
        ),
    ]
