# Generated by Django 4.2.5 on 2025-07-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_assigncourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('100', '100 Level'), ('200', '200 Level'), ('300', '300 Level'), ('400', '400 Level'), ('500', '500 Level')], max_length=3),
        ),
        migrations.AlterField(
            model_name='levelcourse',
            name='level',
            field=models.CharField(choices=[('100', '100 Level'), ('200', '200 Level'), ('300', '300 Level'), ('400', '400 Level'), ('500', '500 Level')], max_length=3),
        ),
        migrations.AlterUniqueTogether(
            name='assigncourse',
            unique_together={('course', 'academic_staff')},
        ),
    ]
