# Generated by Django 4.2.5 on 2025-07-08 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_course_level_alter_levelcourse_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigncourse',
            name='academic_calendar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.academiccalendar'),
            preserve_default=False,
        ),
    ]
