# Generated by Django 4.2.5 on 2025-07-09 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_assigncourse_academic_calendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicstaff',
            name='position',
            field=models.CharField(choices=[('PROF', 'Professor'), ('ASSOC_PROF', 'Associate Professor'), ('SR_LECT', 'Senior Lecturer'), ('LECT_I', 'Lecturer I'), ('LECT_II', 'Lecturer II'), ('ASST_LECT', 'Assistant Lecturer'), ('GRAD_AST', 'Graduate Assistant')], default='GRAD_AST', max_length=20),
        ),
        migrations.AddField(
            model_name='academicstaff',
            name='role',
            field=models.CharField(choices=[('HOD', 'Head of Department'), ('DEAN', 'Dean'), ('EXAM_OFFICER', 'Examination Officer'), ('STAFF', 'Regular Staff')], default='STAFF', max_length=20),
        ),
    ]
