# Generated by Django 4.2.5 on 2025-07-09 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_academicstaff_position_academicstaff_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicstaff',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.department'),
            preserve_default=False,
        ),
    ]
