# Generated by Django 4.2.5 on 2025-07-09 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_academicstaff_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonacademicstaff',
            name='role',
            field=models.CharField(choices=[('REGISTRAR', 'Registrar'), ('BURSAR', 'Bursar'), ('LIBRARIAN', 'Librarian'), ('ICT_OFFICER', 'ICT Officer'), ('SECURITY', 'Security Staff'), ('CLEANER', 'Cleaner'), ('CLERK', 'Clerical Staff'), ('STAFF', 'Regular Staff')], default='STAFF', max_length=20),
        ),
    ]
