# Generated by Django 4.2.5 on 2025-07-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_nonacademicstaff_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='AspirantAcademicCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=20, unique=True)),
                ('is_current', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='nonacademicstaff',
            name='role',
            field=models.CharField(choices=[('REGISTRAR', 'Registrar'), ('ADDMISSION_OFFICER', 'Addmission Officer'), ('BURSAR', 'Bursar'), ('LIBRARIAN', 'Librarian'), ('ICT_OFFICER', 'ICT Officer'), ('SECURITY', 'Security Staff'), ('CLEANER', 'Cleaner'), ('CLERK', 'Clerical Staff'), ('STAFF', 'Regular Staff')], default='STAFF', max_length=20),
        ),
    ]
