# Generated by Django 4.2.5 on 2025-07-10 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_aspirantacademiccalendar_alter_nonacademicstaff_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspirantstudent',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.aspirantacademiccalendar'),
        ),
    ]
