# Generated by Django 4.2.5 on 2025-07-16 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_aspirantstudent_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semesterresult',
            name='session',
        ),
        migrations.AddField(
            model_name='semesterresult',
            name='academic_calendar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.academiccalendar'),
        ),
    ]
