# Generated by Django 4.2.5 on 2025-07-16 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_semesterresult_session_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='semesterresult',
            unique_together={('student', 'academic_calendar')},
        ),
        migrations.RemoveField(
            model_name='semesterresult',
            name='semester',
        ),
    ]
