# Generated by Django 4.2.5 on 2025-07-16 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_semesterresult_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentresult',
            name='grade_point',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='is_released',
        ),
        migrations.AddField(
            model_name='semesterresult',
            name='cgpa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='semesterresult',
            name='gpa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='semesterresult',
            name='is_released',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='semesterresult',
            name='remark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='semesterresult',
            name='total_grade_points',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='semesterresult',
            name='total_units_passed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='semesterresult',
            name='total_units_registered',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='semesterresult',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='semester_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_results', to='core.semesterresult'),
        ),
    ]
