# Generated by Django 4.2.5 on 2025-07-19 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_studentresult_grade_point_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academiccalendar',
            name='semester',
            field=models.CharField(choices=[('First', 'First Semester'), ('Second', 'Second Semester')], max_length=30),
        ),
        migrations.AlterField(
            model_name='academicstaff',
            name='position',
            field=models.CharField(choices=[('PROF', 'Professor'), ('ASSOC_PROF', 'Associate Professor'), ('SR_LECT', 'Senior Lecturer'), ('LECT_I', 'Lecturer I'), ('LECT_II', 'Lecturer II'), ('ASST_LECT', 'Assistant Lecturer'), ('GRAD_AST', 'Graduate Assistant')], default='GRAD_AST', max_length=30),
        ),
        migrations.AlterField(
            model_name='academicstaff',
            name='role',
            field=models.CharField(choices=[('HOD', 'Head of Department'), ('DEAN', 'Dean'), ('EXAM_OFFICER', 'Examination Officer'), ('STAFF', 'Regular Staff')], default='STAFF', max_length=30),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('core', 'Core'), ('elective', 'Elective'), ('general', 'General')], max_length=30),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('100', '100 Level'), ('200', '200 Level'), ('300', '300 Level'), ('400', '400 Level'), ('500', '500 Level')], max_length=30),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(choices=[('First', 'First Semester'), ('Second', 'Second Semester')], max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'Management'), (2, 'AcademicStaff'), (3, 'NonAcademicStaff'), (4, 'Student'), (5, 'AspirantStudent')], default=30, max_length=1),
        ),
        migrations.AlterField(
            model_name='departmentschoolfee',
            name='level',
            field=models.CharField(choices=[('100', '100 Level'), ('200', '200 Level'), ('300', '300 Level'), ('400', '400 Level'), ('500', '500 Level')], max_length=30),
        ),
        migrations.AlterField(
            model_name='levelcourse',
            name='level',
            field=models.CharField(choices=[('100', '100 Level'), ('200', '200 Level'), ('300', '300 Level'), ('400', '400 Level'), ('500', '500 Level')], max_length=30),
        ),
        migrations.AlterField(
            model_name='levelcourse',
            name='semester',
            field=models.CharField(choices=[('First', 'First Semester'), ('Second', 'Second Semester')], max_length=30),
        ),
        migrations.AlterField(
            model_name='nonacademicstaff',
            name='role',
            field=models.CharField(choices=[('REGISTRAR', 'Registrar'), ('ADDMISSION_OFFICER', 'Addmission Officer'), ('BURSAR', 'Bursar'), ('LIBRARIAN', 'Librarian'), ('ICT_OFFICER', 'ICT Officer'), ('SECURITY', 'Security Staff'), ('CLEANER', 'Cleaner'), ('CLERK', 'Clerical Staff'), ('STAFF', 'Regular Staff')], default='STAFF', max_length=30),
        ),
        migrations.AlterField(
            model_name='studentschoolfee',
            name='level',
            field=models.CharField(max_length=30),
        ),
    ]
