# Generated by Django 4.2.5 on 2025-06-22 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AspirantStudent',
        ),
    ]
