# Generated by Django 4.2.5 on 2025-06-27 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_aspirantstudent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
