# Generated by Django 4.2.5 on 2025-06-22 11:11

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_undergraduateapplication_day_of_birth_and_more'),
        ('studentportal', '0004_aspirantstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspirantstudent',
            name='address_1',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aspirantstudent',
            name='address_2',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aspirantstudent',
            name='city',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aspirantstudent',
            name='country',
            field=django_countries.fields.CountryField(default='NG', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aspirantstudent',
            name='course_applied',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.courseofstudy'),
        ),
        migrations.AddField(
            model_name='aspirantstudent',
            name='emergency_address_1',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aspirantstudent',
            name='emergency_address_2',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aspirantstudent',
            name='emergency_city',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aspirantstudent',
            name='emergency_country',
            field=django_countries.fields.CountryField(default='NG', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aspirantstudent',
            name='emergency_email',
            field=models.EmailField(default='placeholder@example.com', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aspirantstudent',
            name='emergency_first_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aspirantstudent',
            name='emergency_last_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aspirantstudent',
            name='emergency_phone_number',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aspirantstudent',
            name='emergency_postal_code',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aspirantstudent',
            name='emergency_relationship',
            field=models.CharField(
                choices=[('B', 'Brother'), ('S', 'Sister'), ('F', 'Father'), ('M', 'Mother'), ('O', 'Other')],
                default='O',
                max_length=15
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aspirantstudent',
            name='phone_number',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aspirantstudent',
            name='postal_code',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aspirantstudent',
            name='referee_address_1',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aspirantstudent',
            name='referee_address_2',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aspirantstudent',
            name='referee_city',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aspirantstudent',
            name='referee_country',
            field=django_countries.fields.CountryField(default='NG', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aspirantstudent',
            name='referee_email',
            field=models.EmailField(default='placeholder@example.com', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aspirantstudent',
            name='referee_first_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aspirantstudent',
            name='referee_last_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aspirantstudent',
            name='referee_phone_number',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aspirantstudent',
            name='referee_postal_code',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aspirantstudent',
            name='referee_state_province',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aspirantstudent',
            name='school_address_1',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aspirantstudent',
            name='school_address_2',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aspirantstudent',
            name='school_city',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aspirantstudent',
            name='school_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aspirantstudent',
            name='school_postal_code',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aspirantstudent',
            name='school_state_province',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aspirantstudent',
            name='school_year_graduated',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aspirantstudent',
            name='state_province',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
