# Generated by Django 4.2.5 on 2025-06-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentportal', '0005_aspirantstudent_address_1_aspirantstudent_address_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspirantstudent',
            name='admission_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('admitted', 'Admitted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
