# Generated by Django 4.2.5 on 2025-06-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentportal', '0006_aspirantstudent_admission_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.PositiveIntegerField(choices=[(100, '100 Level'), (200, '200 Level'), (300, '300 Level'), (400, '400 Level'), (500, '500 Level'), (600, '600 Level')]),
        ),
    ]
